import { MapTypeStyle } from '@agm/core';

export const AgmMapStyes: MapTypeStyle[] = [
  {
    "featureType":"all",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "saturation":36
      },
      {
        "color":"#000000"
      },
      {
        "lightness":40
      }
    ]
  },
  {
    "featureType":"all",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "visibility":"on"
      },
      {
        "color":"#000000"
      },
      {
        "lightness":16
      }
    ]
  },
  {
    "featureType":"all",
    "elementType":"labels.icon",
    "stylers":[
      {
        "visibility":"off"
      }
    ]
  },
  {
    "featureType":"administrative",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "color":"#000000"
      },
      {
        "lightness":20
      }
    ]
  },
  {
    "featureType":"administrative",
    "elementType":"geometry.stroke",
    "stylers":[
      {
        "lightness":17
      },
      {
        "weight":1.2
      }
    ]
  },
  {
    "featureType":"administrative",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "visibility":"simplified"
      }
    ]
  },
  {
    "featureType":"administrative",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "visibility":"simplified"
      }
    ]
  },
  {
    "featureType":"landscape",
    "elementType":"geometry",
    "stylers":[
      {
        "color":"#000000"
      },
      {
        "lightness":20
      }
    ]
  },
  {
    "featureType":"landscape",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "visibility":"on"
      }
    ]
  },
  {
    "featureType":"landscape",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "color":"#ff0000"
      },
      {
        "visibility":"off"
      }
    ]
  },
  {
    "featureType":"landscape",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "visibility":"simplified"
      }
    ]
  },
  {
    "featureType":"poi",
    "elementType":"geometry",
    "stylers":[
      {
        "color":"#000000"
      },
      {
        "lightness":21
      }
    ]
  },
  {
    "featureType":"road",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "visibility":"on"
      },
      {
        "color":"#3da03b"
      }
    ]
  },
  {
    "featureType":"road",
    "elementType":"geometry.stroke",
    "stylers":[
      {
        "color":"#ff0000"
      },
      {
        "visibility":"simplified"
      }
    ]
  },
  {
    "featureType":"road",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "color":"#c4c4c4"
      }
    ]
  },
  {
    "featureType":"road",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "color":"#2c302e"
      }
    ]
  },
  {
    "featureType":"road",
    "elementType":"labels.icon",
    "stylers":[
      {
        "visibility":"off"
      }
    ]
  },
  {
    "featureType":"road.highway",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "lightness":17
      }
    ]
  },
  {
    "featureType":"road.highway",
    "elementType":"geometry.stroke",
    "stylers":[
      {
        "lightness":29
      },
      {
        "weight":0.2
      }
    ]
  },
  {
    "featureType":"road.highway",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "visibility":"on"
      }
    ]
  },
  {
    "featureType":"road.arterial",
    "elementType":"geometry",
    "stylers":[
      {
        "color":"#000000"
      },
      {
        "lightness":18
      }
    ]
  },
  {
    "featureType":"road.arterial",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "color":"#3da03b"
      }
    ]
  },
  {
    "featureType":"road.arterial",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "color":"#2c302e"
      }
    ]
  },
  {
    "featureType":"road.local",
    "elementType":"geometry",
    "stylers":[
      {
        "color":"#000000"
      },
      {
        "lightness":16
      }
    ]
  },
  {
    "featureType":"road.local",
    "elementType":"labels.text.fill",
    "stylers":[
      {
        "color":"#c4c4c4"
      }
    ]
  },
  {
    "featureType":"road.local",
    "elementType":"labels.text.stroke",
    "stylers":[
      {
        "color":"#2c302e"
      }
    ]
  },
  {
    "featureType":"transit",
    "elementType":"geometry",
    "stylers":[
      {
        "lightness":19
      }
    ]
  },
  {
    "featureType":"transit",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "visibility":"off"
      }
    ]
  },
  {
    "featureType":"transit.line",
    "elementType":"geometry.fill",
    "stylers":[
      {
        "visibility":"off"
      }
    ]
  },
  {
    "featureType":"water",
    "elementType":"geometry",
    "stylers":[
      {
        "color":"#474a48"
      },
      {
        "lightness":17
      }
    ]
  }
];